name: "Setup project"
description: "Setup runner environment"

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.local/share/pnpm/store
        key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
