name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: run lint
        run: pnpm lint
      - name: run build
        run: pnpm build
      - name: run tests
        run: pnpm test
