name: release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: ./.github/actions/setup
      - name: create pr / publish release
        uses: changesets/action@v1.7.0
        with:
          commit: "ci: version packages [skip ci]"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
